Country.create!([
  { name: "Abkhazia", nationality:  "Abkhazian"},
  { name: "Afghanistan", nationality:  "Afghan"},
  { name: "Albania", nationality:  "Albanian"},
  { name: "Algeria", nationality:  "Algerian"},
  { name: "American Samoa", nationality:  "American Samoan"},
  { name: "Andorra", nationality:  "Andorran"},
  { name: "Angola", nationality:  "Angolan"},
  { name: "Anguilla", nationality:  "Anguillan"},
  { name: "Antigua and Barbuda", nationality:  "Antiguan/Barbudan"},
  { name: "Argentina", nationality:  "Argentinian"},
  { name: "Armenia", nationality:  "Armenian"},
  { name: "Aruba", nationality:  "Aruban"},
  { name: "Australia", nationality:  "Australian"},
  { name: "Austria", nationality:  "Austrian"},
  { name: "Azerbaijan", nationality:  "Azerbaijani"},
  { name: "Bahamas", nationality:  "Bahamian"},
  { name: "Bahrain", nationality:  "Bahraini"},
  { name: "Bangladesh", nationality:  "Bangladeshi"},
  { name: "Barbados", nationality:  "Barbadian"},
  { name: "Belarus", nationality:  "Belarusian"},
  { name: "Belgium", nationality:  "Belgian"},
  { name: "Belize", nationality:  "Belizean"},
  { name: "Benin", nationality:  "Beninese"},
  { name: "Bermuda", nationality:  "Bermudian"},
  { name: "Bhutan", nationality:  "Bhutanese"},
  { name: "Bolivia", nationality:  "Bolivian"},
  { name: "Bosnia and Herzegovina", nationality:  "Bosnian/Herzegovinian"},
  { name: "Botswana", nationality:  "Botswanan"},
  { name: "Brazil", nationality:  "Brazilian"},
  { name: "British Virgin Islands", nationality:  "British Virgin Island"},
  { name: "Brunei", nationality:  "Bruneian"},
  { name: "Bulgaria", nationality:  "Bulgarian"},
  { name: "Burkina Fasoa", nationality:  "Burkinabè"},
  { name: "Burmab", nationality:  "Burmese"},
  { name: "Burundi", nationality:  "Burundian"},
  { name: "Cambodia", nationality:  "Cambodian"},
  { name: "Cameroon", nationality:  "Cameroonian"},
  { name: "Canada", nationality:  "Canadian"},
  { name: "Cape Verde", nationality:  "Cape Verdean"},
  { name: "Cayman Islands", nationality:  "Caymanian"},
  { name: "Central African Republic", nationality:  "Central African"},
  { name: "Chad", nationality:  "Chadian"},
  { name: "Chile", nationality:  "Chilean"},
  { name: "People's Republic of China", nationality:  "Chinese"},
  { name: "Christmas Island", nationality:  "Christmas Island"},
  { name: "Cocos (Keeling) Islands", nationality:  "Cocos Island"},
  { name: "Colombia", nationality:  "Colombian"},
  { name: "Comoros", nationality:  "Comorian"},
  { name: "Republic of the Congo", nationality:  "Congolese"},
  { name: "Cook Islands", nationality:  "Cook Island"},
  { name: "Costa Rica", nationality:  "Costa Rican"},
  { name: "Côte d'Ivoire", nationality:  "Ivorian"},
  { name: "Croatia", nationality:  "Croatian"},
  { name: "Cuba", nationality:  "Cuban"},
  { name: "Cyprus", nationality:  "Cypriot"},
  { name: "Czech Republic", nationality:  "Czech"},
  { name: "Denmark", nationality:  "Danish"},
  { name: "Djibouti", nationality:  "Djiboutian"},
  { name: "Dominica", nationality:  "Dominicand"},
  { name: "Dominican Republic", nationality:  "Dominicane"},
  { name: "East Timor", nationality:  "Timorese"},
  { name: "Ecuador", nationality:  "Ecuadorian"},
  { name: "Egypt", nationality:  "Egyptian"},
  { name: "El Salvador", nationality:  "Salvadoranf"},
  { name: "England", nationality:  "English"},
  { name: "Equatorial Guinea", nationality:  "Equatoguinean"},
  { name: "Eritrea", nationality:  "Eritrean"},
  { name: "Estonia", nationality:  "Estonian"},
  { name: "Ethiopia", nationality:  "Ethiopian"},
  { name: "Falkland Islands", nationality:  "Falkland Island"},
  { name: "Faroe Islands", nationality:  "Faroese"},
  { name: "Fiji", nationality:  "Fijian"},
  { name: "Finland", nationality:  "Finnish"},
  { name: "France", nationality:  "French"},
  { name: "French Guiana", nationality:  "French Guianese"},
  { name: "French Polynesia", nationality:  "French Polynesian"},
  { name: "Gabon", nationality:  "Gabonese"},
  { name: "Gambia", nationality:  "Gambian"},
  { name: "Georgia", nationality:  "Georgian"},
  { name: "Germany", nationality:  "German"},
  { name: "Ghana", nationality:  "Ghanaian"},
  { name: "Gibraltar", nationality:  "Gibraltar"},
  { name: "Great Britain", nationality:  "British"},
  { name: "Greece", nationality:  "Greek"},
  { name: "Greenland", nationality:  "Greenlandic"},
  { name: "Grenada", nationality:  "Grenadian"},
  { name: "Guadeloupe", nationality:  "Guadeloupe"},
  { name: "Guam", nationality:  "Guamanian"},
  { name: "Guatemala", nationality:  "Guatemalan"},
  { name: "Guinea", nationality:  "Guinean"},
  { name: "Guinea-Bissau", nationality:  "Guinea-Bissau"},
  { name: "Guyana", nationality:  "Guyanese"},
  { name: "Haiti", nationality:  "Haitian"},
  { name: "Honduras", nationality:  "Honduran"},
  { name: "Hong Kong", nationality:  "Hong Kong"},
  { name: "Hungary", nationality:  "Hungarian"},
  { name: "Iceland", nationality:  "Icelandic"},
  { name: "India", nationality:  "Indian"},
  { name: "Indonesia", nationality:  "Indonesian"},
  { name: "Iran", nationality:  "Iranian"},
  { name: "Iraq", nationality:  "Iraqi"},
  { name: "Ireland", nationality:  "Irish"},
  { name: "Isle of Man", nationality:  "Manx"},
  { name: "Israel", nationality:  "Israeli"},
  { name: "Italy", nationality:  "Italian"},
  { name: "Jamaica", nationality:  "Jamaican"},
  { name: "Japan", nationality:  "Japanese"},
  { name: "Jordan", nationality:  "Jordanian"},
  { name: "Kazakhstan", nationality:  "Kazakhstani"},
  { name: "Kenya", nationality:  "Kenyan"},
  { name: "Kiribati", nationality:  "I-Kiribati"},
  { name: "North Korea", nationality:  "North Korean"},
  { name: "South Korea", nationality:  "South Korean"},
  { name: "Kosovo", nationality:  "Kosovan"},
  { name: "Kuwait", nationality:  "Kuwaiti"},
  { name: "Kyrgyzstan", nationality:  "Kyrgyzstani"},
  { name: "Laos", nationality:  "Laotian"},
  { name: "Latvia", nationality:  "Latvian"},
  { name: "Lebanon", nationality:  "Lebanese"},
  { name: "Lesotho", nationality:  "Basotho"},
  { name: "Liberia", nationality:  "Liberian"},
  { name: "Libya", nationality:  "Libyan"},
  { name: "Liechtenstein", nationality:  "Liechtenstein"},
  { name: "Lithuania", nationality:  "Lithuanian"},
  { name: "Luxembourg", nationality:  "Luxembourg"},
  { name: "Macau", nationality:  "Macanese"},
  { name: "Republic of Macedonia", nationality:  "Macedonian"},
  { name: "Madagascar", nationality:  "Malagasy"},
  { name: "Malawi", nationality:  "Malawian"},
  { name: "Malaysia", nationality:  "Malaysian"},
  { name: "Maldives", nationality:  "Maldivian"},
  { name: "Mali", nationality:  "Malian"},
  { name: "Malta", nationality:  "Maltese"},
  { name: "Marshall Islands", nationality:  "Marshallese"},
  { name: "Martinique", nationality:  "Martiniquais"},
  { name: "Mauritania", nationality:  "Mauritanian"},
  { name: "Mauritius", nationality:  "Mauritian"},
  { name: "Mayotte", nationality:  "Mahoran"},
  { name: "Mexico", nationality:  "Mexican"},
  { name: "Micronesia, nationality:  Federated States of"},
  { name: "Moldova", nationality:  "Moldovan"},
  { name: "Monaco", nationality:  "Monacan"},
  { name: "Mongolia", nationality:  "Mongolian"},
  { name: "Montenegro", nationality:  "Montenegrin"},
  { name: "Montserrat", nationality:  "Montserratian"},
  { name: "Morocco", nationality:  "Moroccan"},
  { name: "Mozambique", nationality:  "Mozambican"},
  { name: "Namibia", nationality:  "Namibian"},
  { name: "Nauru", nationality:  "Nauruan"},
  { name: "Nepal", nationality:  "Nepalese"},
  { name: "Netherlands", nationality:  "Dutch"},
  { name: "New Caledonia", nationality:  "New Caledonian"},
  { name: "New Zealand", nationality:  "New Zealand"},
  { name: "Nicaragua", nationality:  "Nicaraguan"},
  { name: "Niue", nationality:  "Niuean"},
  { name: "Niger", nationality:  "Nigerien"},
  { name: "Nigeria", nationality:  "Nigerian"},
  { name: "Norway", nationality:  "Norwegian"},
  { name: "Northern Ireland", nationality:  "British"},
  { name: "Northern Marianas", nationality:  "Northern Marianan"},
  { name: "Oman", nationality:  "Omani"},
  { name: "Pakistan", nationality:  "Pakistani"},
  { name: "Palestine", nationality:  "Palestinian"},
  { name: "Palau", nationality:  "Palauan"},
  { name: "Panama", nationality:  "Panamanian"},
  { name: "Papua New Guinea", nationality:  "Papuan"},
  { name: "Paraguay", nationality:  "Paraguayan"},
  { name: "Peru", nationality:  "Peruvian"},
  { name: "Philippines", nationality:  "Philippine"},
  { name: "Pitcairn Island", nationality:  "Pitcairn Island"},
  { name: "Poland", nationality:  "Polish"},
  { name: "Portugal", nationality:  "Portuguese"},
  { name: "Puerto Rico", nationality:  "Puerto Rican"},
  { name: "Qatar", nationality:  "Qatari"},
  { name: "Republic of Ireland", nationality:  "Irish"},
  { name: "Réunion", nationality:  "Réunionese"},
  { name: "Romania", nationality:  "Romanian"},
  { name: "Russia", nationality:  "Russian"},
  { name: "Rwanda", nationality:  "Rwandan"},
  { name: "St. Helena", nationality:  "St. Helenian"},
  { name: "St. Kitts and Nevis", nationality:  "Kittitian"},
  { name: "St. Lucia", nationality:  "St. Lucian"},
  { name: "Saint-Pierre and Miquelon", nationality:  "Saint-Pierrais"},
  { name: "St. Vincent and the Grenadines", nationality:  "St. Vincentian"},
  { name: "Samoa", nationality:  "Samoan"},
  { name: "San Marino", nationality:  "Sammarinese"},
  { name: "São Tomé and Príncipe", nationality:  "São Toméan"},
  { name: "Saudi Arabia", nationality:  "Saudi Arabian"},
  { name: "Scotland", nationality:  "British"},
  { name: "Senegal", nationality:  "Senegalese"},
  { name: "Serbia", nationality:  "Serbian"},
  { name: "Seychelles", nationality:  "Seychellois"},
  { name: "Sierra Leone", nationality:  "Sierra Leonean"},
  { name: "Singapore", nationality:  "Singaporean"},
  { name: "Slovakia", nationality:  "Slovak"},
  { name: "Slovenia", nationality:  "Slovenian"},
  { name: "Solomon Islands", nationality:  "Solomon Island"},
  { name: "Somalia", nationality:  "Somali"},
  { name: "South Africa", nationality:  "South African"},
  { name: "South Ossetia", nationality:  "South Ossetian"},
  { name: "South Sudan", nationality:  "South Sudanese"},
  { name: "Spain", nationality:  "Spanish"},
  { name: "Sri Lanka", nationality:  "Sri Lankan"},
  { name: "Sudan", nationality:  "Sudanese"},
  { name: "Surinam", nationality:  "Surinamese"},
  { name: "Swaziland", nationality:  "Swazi"},
  { name: "Sweden", nationality:  "Swedish"},
  { name: "Switzerland", nationality:  "Swiss"},
  { name: "Syria", nationality:  "Syrian"},
  { name: "Taiwan", nationality:  "Taiwanese"},
  { name: "Tajikistan", nationality:  "Tajikistani"},
  { name: "Tanzania", nationality:  "Tanzanian"},
  { name: "Thailand", nationality:  "Thai"},
  { name: "Togo", nationality:  "Togolese"},
  { name: "Tonga", nationality:  "Tongan"},
  { name: "Trinidad and Tobago", nationality:  "Trinidadian"},
  { name: "Tunisia", nationality:  "Tunisian"},
  { name: "Turkey", nationality:  "Turkish"},
  { name: "Turkmenistan", nationality:  "Turkmen"},
  { name: "Turks and Caicos Islands", nationality:  "TC"},
  { name: "Tuvalu", nationality:  "Tuvaluan"},
  { name: "Uganda", nationality:  "Ugandan"},
  { name: "Ukraine", nationality:  "Ukrainian"},
  { name: "United Arab Emirates", nationality:  "Emirati"},
  { name: "United Kingdom", nationality:  "British"},
  { name: "United States", nationality:  "American"},
  { name: "Uruguay", nationality:  "Uruguayan"},
  { name: "Uzbekistan", nationality:  "Uzbekistani"},
  { name: "Vanuatu", nationality:  "Vanuatuan"},
  { name: "Venezuela", nationality:  "Venezuelan"},
  { name: "Vietnam", nationality:  "Vietnamese"},
  { name: "Virgin Islands", nationality:  "Virgin Island"},
  { name: "Wales", nationality:  "Welsh"},
  { name: "Wallis and Futuna", nationality:  "Wallisian"},
  { name: "Western Sahara", nationality:  "Sahraw"},
  { name: "Yemen", nationality:  "Yemeni"},
  { name: "Zambia", nationality:  "Zambian"},
  { name: "Zimbabwe", nationality:  "Zimbabwean"},
])
