# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 562e1f6ce07e8a86323e9bbd4e966c55d06232011644bebc65f2495b703785933902f81cc71d3cbc7956225bb35e1b40c35d6154bd28b52257e47b53509a84ab

test:
  secret_key_base: 89652f0d4ddaf5d97b3d8f3dd69be4709ef1854e663461fbfbc015f2e643fc00d954e3279f9327427ddd30d68ee7eac41be980e2b2a65b504321af40c37f9217

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
